### ISSUE TITLE
Open Discussions Feature

### ISSUE THREAD

**Issue by genedan** [casact/meta#3]
Hello, could we please open up the discussions feature on the casact GitHub page? I think this will boost user and community engagement, just a tiny bit.

**Comment by ResearchActuary** [comment]
Tell me more about discussions? Not yet familiar with it.

**Comment by genedan** [comment]
It's a feature that if enabled, adds a small forum to the organization. You go to organization settings -> discussions -> enable discussions. You need to select a repo as the host.

I think this would allow people who aren't official members of the organization to create threads, and ask general questions without having to create issues, which would be helpful if they are new to GitHub. I'm not sure if enabling discussions for an org makes it available to anyone on GitHub - but I do know that is the case for the individual repos that have it enabled (like chainladder).

**Comment by ResearchActuary** [comment]
I have changed this setting. Looking forward to seeing some discussions on this repo.
